---
name: Build and deploy page

# yamllint disable rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  pages: write

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Clone react project
        run: git clone https://github.com/waldiez/react.git
      - name: Install dependencies and build the site
        run: |
          bun install
          echo "BASE_URL=/" > .env
          echo "VITE_VS_PATH=vs" >> .env
          bun build:site
          mv out/static ../site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
